# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='participantId',
            field=models.BigIntegerField(default=1),
        ),
    ]
