# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 10:56
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_namemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='VogabyggdModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jsonData', jsonfield.fields.JSONField()),
                ('participantName', models.CharField(max_length=50)),
                ('participantId', models.BigIntegerField(default=1)),
            ],
        ),
    ]
